name: CI

on: [push, pull_request]

jobs:
    build-vscode:
        strategy:
            matrix:
                os: [macos-latest, ubuntu-latest, windows-latest]

        runs-on: ${{ matrix.os }}

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x

            - name: Install dependencies
              working-directory: ./vscode
              run: npm install

            - name: Lint
              working-directory: ./vscode
              run: npm run lint

            - name: Build
              working-directory: ./vscode
              run: npm run build

            - name: Test
              uses: GabrielBB/xvfb-action@v1.0
              with:
                  working-directory: ./vscode
                  run: npm run test
