name: Publish Visual Studio 2022 Extension

on: workflow_dispatch

jobs:
    publish-visual-studio:
        runs-on: windows-2022

        env:
            Configuration: Release
            DeployExtension: false

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup MSBuild
              uses: microsoft/setup-msbuild@v1.0.2

            - name: Publish
              working-directory: ./visual-studio
              run: msbuild source/GitWebLinks/GitWebLinks.csproj /t:PublishToMarketplace /Restore /v:Minimal /p:Configuration=Release /p:PersonalAccessToken=${{ secrets.PUBLISHER_TOKEN }}
